spring:
    application:
        name: MS-WELCOME-API
    boot:
        admin:
            client:
                url: http://localhost:1111/

management:
    endpoints:
        web:
            exposure:
                include: '*'
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
        
server:
  port: 8082