spring:
    application:
        name: MS-GREET-API
    boot:
        admin:
            client:
                url: http://localhost:1111/

management:
    endpoints:
        web:
            exposure:
                include: '*'
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


  
server:
   port: 9091

  
 